### ISSUE TITLE
Add versions to shard.yml

### ISSUE THREAD

**Issue by faustinoaq** [luckyframework/web#176]
Hi @paulcsmith ! :)

Currently Lucky is always using latest version, I think is because this project is on early development phase.

However when Lucky become in stable we should add version numbers to avoid annoying shards errors,

Current `shard.yml`:

```yaml
dependencies:
  lucky_cli:
    github: luckyframework/cli
  habitat:
    github: luckyframework/habitat
    version: "~> 0.2.0"
  lucky_record:
    github: luckyframework/record
  lucky_router:
    github: luckyframework/router
  shell-table:
    github: jwaldrip/shell-table.cr

crystal: 0.20.3
```

First stable `shard.yml` :)

```yaml
dependencies:
  lucky_cli:
    github: luckyframework/cli
    version: "~> 1.0.0"
  habitat:
    github: luckyframework/habitat
    version: "~> 1.0.0"
  lucky_record:
    github: luckyframework/record
    version: "~> 1.0.0"
  lucky_router:
    github: luckyframework/router
    version: "~> 1.0.0"
  shell-table:
    github: jwaldrip/shell-table.cr
    version: "~> 1.0.0"

crystal: 1.0.0
```
